name: patterns
description: "Project for patterns"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  audioplayers: ^6.0.0
  file_picker: 10.3.3
  permission_handler: ^12.0.1
  shared_preferences: 2.5.3
  web_socket_channel: ^3.0.3
  flutter_webrtc: 1.2.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  #assets:
 #   - assets/audio/
